[tool.poetry]
name = "pypropel"
version = "0.1.7"
description = ""
authors = ["Jianfeng Sun <jianfeng.sunmt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
pandas = "^2.2.2"
biopython = "^1.84"
seaborn = "^0.13.2"
matplotlib = "^3.9.1"
scikit-learn = "^1.5.1"
mini3di = "^0.2.1"
click = "^8.2.1"
torch = { version = ">=2.0.0", optional = true }
fair-esm = { version = ">=2.0.0", optional = true }

[tool.poetry.extras]
esm = ["torch", "fair-esm"]

[tool.poetry.scripts]
pypropel_struct_check_cplx = "pypropel.prot.structure.distance.isite.check.Complex:cli"
pypropel_struct_dist_cplx1 = "pypropel.prot.structure.distance.isite.DistanceComplexOne:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
